function [LongContourMap,edge_map]=GetLongContour(img, lengthTH, edgeTh, edge_map)
%GETLONGCONTOUR extract the contour whose length is larger than lengthTH
%Output: 
%   LongContourMap - A binary image shows where long contours are. 
%       1, for long contours
%       0, otherwise   
%   edge_map - Generated by the structured edge detection: 
%       "Structured Forests for Fast Edge Detection" by Piotr Dollar and C. Lawrence Zitnick
   
    if ~exist('lengthTH', 'var')
        lengthTH = 10 ;
    end
    if ~exist('edge_map', 'var')
        % structured edge detection
        % Need Piotr's Computer Vision Matlab Toolbox
        setParametersSED ;
        edge_map = edgesDetect(img, model) ;
    end
    if ~exist('edgeTh',  'var')
        edgeTh = 0.1 ;
    end
    
    %%% edge extension
    extRange = 4 ;
    bin_edge_map = edgeExtension(edge_map>edgeTh, extRange) ;
    
    %%% find long contours
    [L, num] = bwlabel(bin_edge_map) ;
    LongContourMap = bin_edge_map ;
    for i=1:num
        ind = find(L==i) ;
        EdgeSize = length(ind) ;
        if EdgeSize<lengthTH
            LongContourMap(ind) = 0 ;
        end
    end
end